# Generated by Django 3.2.6 on 2021-08-14 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', django_cryptography.fields.encrypt(models.CharField(max_length=255))),
                ('name', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='credential',
            constraint=models.CheckConstraint(check=models.Q(('name__length__gt', 0)), name='length_credential_name'),
        ),
        migrations.AddConstraint(
            model_name='credential',
            constraint=models.UniqueConstraint(fields=('user', 'token'), name='unique_credential_token'),
        ),
        migrations.AddConstraint(
            model_name='credential',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_credential_name'),
        ),
    ]
