# Generated by Django 3.2.6 on 2021-08-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_credential_token_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='credential',
            constraint=models.CheckConstraint(check=models.Q(('token_type__length__gt', 0)), name='length_credential_tokentype'),
        ),
    ]
