# Generated by Django 3.1.7 on 2021-05-08 18:07

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', django_cryptography.fields.encrypt(models.CharField(max_length=255))),
                ('name', models.CharField(max_length=120)),
            ],
        ),
    ]
