# Generated by Django 3.2.6 on 2021-08-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='token_type',
            field=models.CharField(choices=[('PLAID_CLIENT_ID', 'Plaid Client ID'), ('PLAID_CLIENT_SECRET', 'Plaid Client Secret'), ('PLAID_PUBLIC_KEY', 'Plaid Public Key'), ('PLAID_TOKEN', 'Plaid Token')], default='PLAID_CLIENT_ID', max_length=50),
            preserve_default=False,
        ),
    ]
