# Generated by Django 3.1.7 on 2021-05-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_credential_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='credential',
            constraint=models.CheckConstraint(check=models.Q(name__length__gte=0), name='length_credential_name'),
        ),
        migrations.AddConstraint(
            model_name='credential',
            constraint=models.UniqueConstraint(fields=('user', 'token'), name='unique_credential_token'),
        ),
        migrations.AddConstraint(
            model_name='credential',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_credential_name'),
        ),
    ]
