# Generated by Django 3.1.7 on 2021-05-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_auto_20210508_1914'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='credential',
            name='length_credential_name',
        ),
        migrations.AddConstraint(
            model_name='credential',
            constraint=models.CheckConstraint(check=models.Q(name__length__gt=0), name='length_credential_name'),
        ),
    ]
